# Example file need to be adapted to the compose file above
# Note this is temporary and security key provided are false and should be 
# Based on doc https://docs.konghq.com/gateway/latest/production/deployment-topologies/db-less-and-declarative-config/
# For jwt plugin https://docs.konghq.com/hub/kong-inc/jwt/how-to/basic-example/
# To use jwt from oauth https://docs.konghq.com/hub/kong-inc/jwt/#using-the-jwt-plugin-with-auth0
_format_version: "3.0"
_transform: true

services:
- name: medical-api
  url: http://10.1.1.3:5000
  routes:
  - name: invetory-medical
    paths:
    - /medical
    methods:
    - GET
    - POST
  - name : get-medical-specific
    paths:
    - /medical/{id}
    methods:
    - GET

- name: authentification-api
  url: http://10.1.1.5:5000
  routes:
  - name: basic-logging
    paths:
    - /auth/login/basic
    methods:
      - POST
  - name : advanced-logging
    paths:
      - /auth/login
    methods:
    - POST
  - name : code-validation
    paths:
      - /auth/api/code/validation
    methods:
      - POST
  - name: swagger
    paths:
      - /auth/swagger-ui/index.html
    methods:
      - GET